[workspace]
members = [
    "async-fileio",
    "substrate-design-patterns",
    # "subspace-sdk-playground",
    # "rocksdb",
    # "trie",
    # "libp2p",
]
# considering all the projects are following rust 2021.
resolver = "2"